### ISSUE TITLE
Unknown tag render

### ISSUE THREAD

**Issue by Harsha-Madiraju** [harrydeluxe/php-liquid#67]
<br />
<b>Fatal error</b>:  Uncaught Liquid\Exception\ParseException: Unknown tag render in /Applications/MAMP/htdocs/ehr_uphc/liquid/src/Liquid/AbstractBlock.php:210
Stack trace:
#0 /Applications/MAMP/htdocs/ehr_uphc/liquid/src/Liquid/AbstractBlock.php(88): Liquid\AbstractBlock-&gt;unknownTag('render', ''ObservationVit...', Array)
#1 /Applications/MAMP/htdocs/ehr_uphc/liquid/src/Liquid/Document.php(32): Liquid\AbstractBlock-&gt;parse(Array)
#2 /Applications/MAMP/htdocs/ehr_uphc/liquid/src/Liquid/Template.php(213): Liquid\Document-&gt;__construct(Array, Object(Liquid\LocalFileSystem))
#3 /Applications/MAMP/htdocs/ehr_uphc/liquid/src/Liquid/Template.php(188): Liquid\Template-&gt;parseAlways('{\n    &quot;resource...')
#4 /Applications/MAMP/htdocs/ehr_uphc/liquid/OPConsultRecord.php(194): Liquid\Template-&gt;parse('{\n    &quot;resource...')
#5 {main}
  thrown in <b>/Applications/MAMP/htdocs/ehr_uphc/liquid/src/Liquid/AbstractBlock.php</b> on line <b>210</b><br />

**Comment by schmoove** [comment]
This implementation of Liquid doesn't offer a `render` tag. You'll need to create a custom one.
